version: "3.7"
services:
    app:
        build: ./
        ports:
            - 80:80
            - 443:443
        environment:
            MULTI_TENANCY: 'true'
            MASTER_DB_HOST: ${MASTER_DB_HOST:-db}
            MASTER_DB_DATABASE: ${MASTER_DB_DATABASE:-swsistemas}
            MASTER_DB_USER: ${MASTER_DB_USER:-root}
            MASTER_DB_PASSWORD: ${MASTER_DB_PASSWORD:-root}
            XDEBUG_MODE: ${XDEBUG_MODE:-debug}
            OAUTH_ENCRYPTION_KEY: ${OAUTH_ENCRYPTION_KEY}
            S3_ACCESS_KEY: ${S3_ACCESS_KEY}
            S3_ACCESS_SECRET: ${S3_ACCESS_SECRET}
            S3_REGION: ${S3_REGION}
            S3_BUCKET: ${S3_BUCKET}
            S3_ENDPOINT: ${S3_ENDPOINT}
            CDN_URL: ${CDN_URL}
            AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
            AUTH0_DOMAIN: ${AUTH0_DOMAIN}
            AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
            AUTH0_COOKIE_SECRET: ${AUTH0_COOKIE_SECRET}
        volumes:
            - ./:/app
            - ./storage:/app/storage
            - ./docker/php-fpm/php.development.ini:/usr/local/etc/php/php.ini
            - ./docker/logs/php-fpm:/var/log/php-fpm
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - db
        networks:
            - default
            - sweduc
    db:
        image: mariadb:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE:-swsistemas}'
            MYSQL_USER: '${DB_USER:-root}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-root}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - ./docker/mysql/dump:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
        networks:
            - default
            - sweduc
    db-testes:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'teste'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'teste'
            MYSQL_USER: 'teste'
            MYSQL_PASSWORD: 'teste'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        tmpfs:
            - /run/mysqld:uid=999,gid=999
            - /tmp
            - /var/lib/mysql
        networks:
            - default
            - sweduc
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_USER: '${DB_USER:-root}'
            PMA_PASSWORD: '${DB_PASSWORD:-root}'
            UPLOAD_LIMIT: 2G
        ports:
            - "8091:80"
        depends_on:
            - db
    docs:
        image: squidfunk/mkdocs-material
        ports:
            - 8000:8000
        volumes:
            - ./docs/mkdocs.yml:/docs/mkdocs.yml
            - ./docs:/docs/docs
volumes:
    mysql-data:
        driver: local

networks:
    sweduc:
        name: sweduc
