
interface Rematricula {
    id: string | number,
    aluno_id: string | number,
    aluno_nome: string | number,
    aluno_num: string | number,
    matricula_inicial_id: string | number,
    matricula_serie: string | number,
    matricula_curso: string | number,
    matricula_unidade: string | number,
    anamnese_atualizada_em: Date,
    assinatura_digital_em: Date,
    contrato_id: string | number,
    created_at: Date,
    dados_atualizados_em: Date,
    documentacao_aprovada_em: Date,
    documentacao_reprovada_em: Date,
    documentos: string | number,
    aprovar_docs_qtd: string | number,
    etapa_atual: string | number,
    nova_matricula: Matricula,
    problemas_rematricula: {
        requerimentos: string[],
        avisos: string[],
    },
    pessoa_responsavel_id: string | number,
    requisicao_de_assinatura_id: string | number,
    seguro_escolar: string | number,
    status: string | number,
    titulo_id: string | number,
    titulo_pago_em: Date,
    updated_at: Date,
    deleted_at: Date,
}
